services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_db &&
             python manage.py runserver 0.0.0.0:8000"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevent node_modules from being overwritten by the bind mount
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
